# Character mapping for OCR Deobfuscation System
# Format: 'standard_character': [list, of, obfuscated, variants]

# Lowercase letters
'a': ['@', 'α', '4', 'а', 'ɑ', 'ä', 'á', 'à', 'â', 'ă', 'å']
'b': ['ƅ', '6', 'б', 'ь', 'β', 'þ', 'ß']
'c': ['©', '¢', 'ç', 'с', 'ć', 'č']
'd': ['đ', 'ð', 'ď', 'ɗ', 'δ']
'e': ['3', '€', 'ε', 'έ', 'е', 'ë', 'é', 'è', 'ê', 'ě', 'ĕ']
'f': ['ƒ', 'ƭ', 'φ', 'ф']
'g': ['9', 'ğ', 'ģ', 'ǥ', 'γ']
'h': ['һ', 'ħ', 'ɦ', 'н']
'i': ['1', '!', '|', 'ı', 'ί', 'и', 'î', 'ï', 'í', 'ì', 'į']
'j': ['ј', 'ʝ']
'k': ['κ', 'к', 'ķ']
'l': ['1', '|', 'ł', 'ľ', 'ĺ', 'ļ']
'm': ['м', 'ɱ', 'ʍ']
'n': ['ñ', 'η', 'и', 'ń', 'ň', 'ņ']
'o': ['0', 'ο', 'σ', 'о', 'ö', 'ó', 'ò', 'ô', 'ø']
'p': ['ρ', 'р', 'þ']
'q': ['ԛ', 'ʠ']
'r': ['я', 'г', 'ř', 'ŕ']
's': ['5', '$', 'ѕ', 'ś', 'š', 'ş']
't': ['+', '†', 'τ', 'т', 'ť', 'ţ']
'u': ['µ', 'υ', 'ц', 'ü', 'ú', 'ù', 'û', 'ů']
'v': ['ν', 'ʋ', 'ѵ']
'w': ['ω', 'ш', 'щ', 'ŵ']
'x': ['×', 'χ', '×', 'х']
'y': ['ý', 'ÿ', 'γ', 'у']
'z': ['2', 'ƶ', 'ž', 'ź', 'ż']

# Uppercase letters
'A': ['4', 'Λ', 'А', 'Ä', 'Á', 'À', 'Â', 'Å']
'B': ['8', 'Β', 'В', 'ß']
'C': ['Ç', 'С', 'Ć', 'Č']
'D': ['Đ', 'Ð', 'Ď']
'E': ['3', 'Ε', 'Е', 'Ë', 'É', 'È', 'Ê', 'Ě']
'F': ['Φ', 'Ф']
'G': ['6', 'Γ', 'Ğ', 'Ģ']
'H': ['Η', 'Н']
'I': ['1', '|', 'Ί', 'И', 'Î', 'Ï', 'Í', 'Ì']
'J': ['Ј']
'K': ['Κ', 'К', 'Ķ']
'L': ['Ł', 'Ľ', 'Ĺ', 'Ļ']
'M': ['Μ', 'М']
'N': ['Ν', 'Ñ', 'Н', 'Ń', 'Ň', 'Ņ']
'O': ['0', 'Ο', 'О', 'Ö', 'Ó', 'Ò', 'Ô', 'Ø']
'P': ['Ρ', 'Р']
'Q': ['Ԛ']
'R': ['Я', 'Ř', 'Ŕ']
'S': ['5', '$', 'Ѕ', 'Ś', 'Š', 'Ş']
'T': ['+', 'Τ', 'Т', 'Ť', 'Ţ']
'U': ['Υ', 'Ü', 'Ú', 'Ù', 'Û', 'Ů']
'V': ['Ν', 'Ѵ']
'W': ['Ω', 'Ш', 'Ŵ']
'X': ['Χ', 'Х']
'Y': ['Υ', 'Ý', 'Ÿ']
'Z': ['Ζ', 'Ž', 'Ź', 'Ż']

# Numbers
'0': ['O', 'o', 'О', 'Ο', 'ο']
'1': ['I', 'l', 'i', '|', 'І']
'2': ['Z', 'z', 'ƻ']
'3': ['E', 'e', 'ε', 'Ε']
'4': ['A', 'a', 'Λ']
'5': ['S', 's', '$']
'6': ['G', 'g', 'б']
'7': ['T', 't', '†']
'8': ['B', 'ß']
'9': ['g', 'q', 'ԛ']

# Common symbols
'@': ['a', 'α', 'а']
'$': ['S', 's', '5']
'&': ['&amp;']
'%': ['⁒', '℅']
'.': ['․', '·', '⋅', '٠']
',': ['‚', '̦']
'-': ['‐', '−', '—', '–']
'_': ['̲', '̱']
'!': ['i', 'І', '|', '¡']
'?': ['¿']
'/': ['⁄', '∕', '∕']
'(': ['❨', '﴾', '₍', '⟨']
')': ['❩', '﴿', '₎', '⟩']
'[': ['⟦', '〚']
']': ['⟧', '〛'] 