# Configuration for OCR Deobfuscation Model

# Model Architecture Configuration
model:
  name: "OCRDeobfuscatorCNN"
  architecture: "unet"  # Options: "unet", "resnet", "autoencoder"
  input_shape: [64, 64, 1]  # Height, Width, Channels
  input_channels: 1
  output_channels: 1
  filters:
    - 64
    - 128
    - 256
    - 512
  dropout_rate: 0.2
  use_batch_norm: true
  activation: "relu"
  final_activation: "sigmoid"

# Training Configuration
training:
  batch_size: 64
  epochs: 100
  early_stopping_patience: 10
  learning_rate: 0.001
  optimizer: "adam"  # Options: "adam", "sgd", "rmsprop"
  lr_scheduler: "reduce_on_plateau"  # Options: "reduce_on_plateau", "step", "cosine", "none"
  lr_scheduler_params:
    patience: 5
    factor: 0.5
    min_lr: 0.00001
  weight_decay: 0.0001
  clip_grad_norm: 1.0
  mixed_precision: true
  save_best_only: true
  save_frequency: 5  # Save every N epochs

# Loss Function Configuration
loss:
  name: "bce_dice"  # Options: "bce", "dice", "bce_dice", "focal", "ssim", "mse"
  weights:  # Weights for combined losses
    bce: 0.5
    dice: 0.5
  focal_params:  # Parameters for focal loss
    gamma: 2.0
    alpha: 0.25

# Data Configuration
data:
  image_size: 64
  gray_scale: true
  normalize: true
  augmentation: true
  augmentation_params:
    rotation_range: 10
    width_shift_range: 0.1
    height_shift_range: 0.1
    zoom_range: 0.1
    horizontal_flip: false
    vertical_flip: false
    brightness_range: [0.9, 1.1]
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

# Inference Configuration
inference:
  threshold: 0.5  # Threshold for binarizing predictions
  post_processing: true
  post_processing_params:
    denoise: true
    morphology: "none"  # Options: "none", "erode", "dilate", "open", "close"
    kernel_size: 3

# Evaluation Configuration
evaluation:
  metrics:
    - "pixel_accuracy"
    - "dice_coef"
    - "iou"
    - "ssim"
    - "ocr_accuracy"
  pipeline_comparison: true
  confusion_matrix: true
  visualize_samples: 20

# Logging and Output Configuration
logging:
  log_dir: "logs"
  tensorboard: true
  log_images_frequency: 5  # Log images every N epochs
  verbose: 2  # 0 = silent, 1 = progress bar, 2 = one line per epoch

# Reproducibility Configuration
reproducibility:
  seed: 42
  deterministic: true 